# Install on-prem server

- hosts: general
  gather_facts: yes
  vars:
    mde_channel: prod
    mde_managed_file: /etc/opt/microsoft/mdatp/managed/mdatp_managed.json
  tasks:
    - include: ../roles/mde_setup_add_repo.yml
    - include: ../roles/omi_install.yml