- name: Install Azure Arc APT package
  apt:
    name: azcmagent
    state: latest
    update_cache: yes
  when: ansible_os_family == "Debian"
- name: Install MDE YUM package
  yum:
    name: azcmagent
    state: latest
    enablerepo: packages-microsoft-com-prod
  when: ansible_os_family == "RedHat"