# This is a basic workflow that is manually triggered

name: Scan images on demand = Defender for Cloud

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Scans Images on Demand"
        default: ""
        required: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ImageScanning:
    runs-on: ubuntu-latest
    steps:  
      - uses: Azure/container-scan@v0
        name: Scan Squid Image
        id: container-scan
        continue-on-error: true
        with:
          image-name: sameersbn/squid:latest
      - uses: Azure/container-scan@v0
        name: Scan VyControl Image
        id: container-scan
        continue-on-error: true
        with:
          image-name: robertoberto/vycontrol:latest
