name: Azure Container Scan

on:
  workflow_dispatch:
    inputs:
      imageName:
        description: "Container image to Scan"
        default: "<url>/<imageName>:<version>"
        required: true

jobs:
  scanContainerImage:
    runs-on: ubuntu-latest
    steps:
      - name: Container image scan Squid
        id: container-scan
        continue-on-error: true
        uses: Azure/container-scan@v0.1
        with:
          image-name: ${{ github.event.inputs.imageName }}
      - name: Post logs to appinsights
        uses: Azure/publish-security-assessments@v0
        with:
          scan-results-path: ${{ steps.container-scan.outputs.scan-report-path }}
          connection-string: ${{ secrets.AZ_APPINSIGHTS_CONNECTION_STRING }}
          subscription-token: ${{ secrets.AZ_SUBSCRIPTION_TOKEN }}
